name: "Terraform Infrastructure"

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        run: |
          # Pehle check karo folder hai ya nahi
          if [ -d "terraform" ]; then
            cd terraform && terraform init
          elif [ -d "Doctor_Ai/terraform" ]; then
            cd Doctor_Ai/terraform && terraform init
          else
            echo "Folder not found! Listing files for debug:"
            ls -R
            exit 1
          fi
      - name: Terraform Init
        run: terraform init
        working-directory: Doctor_Ai/terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: Doctor_Ai/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: Doctor_Ai/terraform